apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    app: limbo
    environment: production   
  name: limbo-rc
  namespace: default
spec:
  replicas: 1
  selector:
    app: limbo
    environment: production   
  template:
    metadata:
      labels:
        app: limbo
        environment: production    
    spec:
      volumes:
      - name: "env-secrets"
        secret:
          secretName: "limbo-secret-env-vars"
      containers:
        - image: petergrace/limbo:latest
        imagePullPolicy: Always
        name: limbo
        resources: {}
        volumeMounts:
          - name: "env-secrets"
            mountPath: "/tmp/secrets"
            readOnly: true  
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
